// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpciX1npZ3t4zyyY4vy7-AiB-IhfWV_pE',
    appId: '1:19946577457:android:bde980310107bb7879ff10',
    messagingSenderId: '19946577457',
    projectId: 'ciftlikpro-79eec',
    databaseURL: 'https://ciftlikpro-79eec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ciftlikpro-79eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68w_-MY08SYCSaDCb_bkO9fCwJItA-iA',
    appId: '1:19946577457:ios:b7a08518a6a67d4779ff10',
    messagingSenderId: '19946577457',
    projectId: 'ciftlikpro-79eec',
    databaseURL: 'https://ciftlikpro-79eec-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ciftlikpro-79eec.firebasestorage.app',
    iosBundleId: 'com.ciftlikpro.app',
  );
}
